# In-Class: September 19, 2018


## Part 1 (You can do this with or without dplyr)

1. The data set at rnf6080.dat records hourly rainfall at a certain location in Canada, every day from 1960 to 1980. First, we need to load the data set into R using the command read.table(). Use the help function to learn what arguments this function takes. Once you have the necessary input, load the data set into R and make it a data frame called rain.df.
2. How many rows and columns does rain.df have? (If there are not 5070 rows and 27 columns, something is wrong; check the previous part to see what might have gone wrong in the previous part.)
3. What are the names of the columns of rain.df?
4. What is the value of row 5, column 7 of rain.df?
5. Display the second row of rain.df in its entirety.
6. Explain what the command below doesby running it on your data and examining the object. (You may find the display functions head() and tail() useful here.) Is it clear now what the last 24 columns represent?
```
names(rain.df) <- c("year","month","day",seq(0,23))
````
7. Create a new column in the data frame called daily, which is the sum of the rightmost 24 columns. With this column, create a histogram of the values in this column, which are supposed to be daily rainfall values. What is wrong with this picture?
8. Create a new data frame rain.df.fixed that takes the original and fixes it for the apparent flaw you have discovered. Having done this, produce a new histogram with the corrected data and explain why this is more reasonable.

## Part 2
### New York City Flights 13

- `flights` [336,776 x 16]. Every flight leaving NYC in 2013.
- `weather` [ 8719 x 14]. Hourly Weather Data.
- `planes` [3322 x 9]. Plane data.
- `airports` [1397 x 7]. Airport data.


```
library(nycflights13)
library(dplyr)
flights
```

### Basic Dplyr

The `dplyr` package uses verbs to perform data manipulation.

- `filter()` and `slice()`
- `arrange()`
- `select()` and `rename()`
- `distinct()`
- `mutate()` and `transmute()`
- `sample_n()` and `sample_frac()`

### Filtering Rows

1. Filter all flights on your birthday.
2. Filter all flights in rows 567 - 589


### Arranging Rows
3. Use arrange() to order the data by year, month and day
4. Use desc() to arrange flights by arrival delay.


### Select
5. Select columns containing data information.
6. Select columns including only plane information.
7. Rename tailnum to tail_num


### Mutating Rows
8. Create a variable called gain which describes the difference between arrival delap and departure delay.
9. Create a variable called speed which is distance over time in hours.


###Summarise
10. Summarise the average delay for all flights.

## Overall Questions

11. Split the complete dataset into individual planes and then summarise each plane by counting the number of flights (count = n()) and computing the average distance and arrival delay . Then plot this:

```
ggplot(delay, aes(dist, delay)) +
  geom_point(aes(size = count), alpha = 1/2) +
  geom_smooth() +
  scale_size_area()
```
12. Find the number of planes and the number of flights that go to each possible destination.

### More Difficult

In the videos we learned about piping our commands. The goal of piping is to help use with the flow of our analysis. The steps we take are:
- Think about it. 
- Describe it. 
- Do it.

13. Consider the code Below:

```
filter(
  summarise(
    select(
      group_by(flights, year, month, day),
      arr_delay, dep_delay
    ),
    arr = mean(arr_delay, na.rm = TRUE),
    dep = mean(dep_delay, na.rm = TRUE)
  ),
  arr > 30 | dep > 30
)
```

a. What are some problems with this function?
b. How easy is it to follow the logic of this?
c. Rewrite this using piping to make it more understandable.
d. Does your rewritten command give the same results?

14. Consider the code below

```
hourly_delay <- filter(
  summarise(
    group_by(
      filter(
        flights, 
        !is.na(dep_delay)
      ),
      date, hour
    ),
    delay=mean(dep_delay),
    n=n()
  ),
  n>10
)
```

1. What are some problems with this function?
b. How easy is it to follow the logic of this?
c. Rewrite this using piping to make it more understandable.
d. Does your rewritten command give the same results?


**Consider how to join information from the other datasets in the package with the current information. Is there a way to tell if weather affected the departure time? Ask yourself other questions about this data and then answer them below.**